name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build site
        env:
          NODE_ENV: production
        run: npm run build
        
      - name: List dist directory
        run: |
          echo "Contents of dist directory:"
          ls -la dist/
          echo "\nContents of dist/pages directory (if exists):"
          ls -la dist/pages || true
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          enable_jekyll: false
          force_orphan: true 